# fly.toml file generated for kasif-backend on 2023-04-09T15:43:15+03:00

app = "kasif-backend"
kill_signal = "SIGINT"
kill_timeout = 5
[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"
primary_region = "otp"
processes = []

[build]
  dockerfile = "dockerfile"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
